#arquivo de configuracoes local/default

#port config
server:
  port: 8090

#define which application will executed
spring:
  application:
    name: "contactbook"

  #database configs - connect to database into the Docker
  datasource:
    url: jdbc:postgresql://localhost:15432/contactbook?currentSchema=public
    username: "admin"
    password: "admin"
    driver-class-name: "org.postgresql.Driver"
    hikari:
      schema: public

#jpa configs
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #flyway config - execute all scripts sql from resources/db.migration to database
  flyway:
    locations: "db/migration"
    baseline-on-migrate: false

#devtools config - to automatic compile our app
  devtools:
    restart:
      enabled: true

#swagger config - makes available our API through swagger
springdoc:
  swagger-ui:
    path: "/contactbook/swagger-ui.html"

#viacep url endpoint - API used in the ViaCepClient
viacep:
  endpoint: "viacep.com.br/ws"